name: Update ReadMe
run-name: README - ${{ github.actor }} by ${{ github.event_name }} ${{ github.ref }}
on:
  push:
    branches:
      - "main"
    paths:
      - "README.md"

jobs:
  docker:
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v2

      # - uses: dorny/paths-filter@v2
      #   id: filter
      #   with:
      #     filters: |
      #       ubuntu:
      #         - 'ubuntu-core/README.md'
      #       tintin:
      #         - 'tintin/README.md'
      #       alpine:
      #         - 'alpine-core/README.md'

      - name: alpine Docker Hub Description
        # if: ${{ steps.filter.outputs.alpine == 'true' }}
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: faliarin/alpine-core
          readme-filepath: README.md

